(()=>{
  const copy={
    zh:{brand:'加密钱包安全指南',label:'更顺畅的浏览体验',title:'建议使用 Safari 打开',titleOther:'建议使用系统浏览器打开',intro:'如果你是在 iPhone 的内置浏览器中打开，Safari 通常能提供更完整的网页体验。你也可以直接在当前浏览器继续。',banner:'独立的加密钱包安全教育指南',steps:'点击“复制链接”，打开 Safari 并粘贴网址即可访问。若系统允许，也可以尝试下方的打开按钮。',open:'尝试在 Safari 打开',openOther:'尝试在默认浏览器打开',copy:'复制网页链接',continue:'继续浏览本页',foot:'本页不会连接钱包，也不会索取助记词、私钥或 PIN。',copied:'链接已复制，请粘贴到 Safari 打开。',failed:'无法自动复制，请使用浏览器菜单复制当前网址。'},
    en:{brand:'Crypto Wallet Safety Guide',label:'A smoother browsing experience',title:'Open in Safari for the best experience',titleOther:'Open in your preferred browser',intro:'On iPhone, Safari may provide a more complete experience than some in-app browsers. You can also continue here in your current browser.',banner:'Independent crypto wallet safety education',steps:'Copy the link, open Safari and paste the address. If your device allows it, you can also try the button below.',open:'Try opening in Safari',openOther:'Try opening in your browser',copy:'Copy page link',continue:'Continue in this browser',foot:'This guide does not connect to wallets or ask for recovery phrases, private keys or PINs.',copied:'Link copied. Paste it into Safari to open.',failed:'Could not copy automatically. Use your browser menu to copy this page address.'},
    es:{brand:'Guía de seguridad para wallets',label:'Una experiencia de navegación más fluida',title:'Abre la página en Safari',titleOther:'Abre la página en tu navegador habitual',intro:'En iPhone, Safari puede ofrecer una experiencia más completa que algunos navegadores integrados en otras apps. También puedes continuar aquí.',banner:'Educación independiente sobre seguridad de wallets',steps:'Copia el enlace, abre Safari y pega la dirección. Si tu dispositivo lo permite, prueba también el botón de abajo.',open:'Probar a abrir en Safari',openOther:'Probar a abrir en el navegador',copy:'Copiar enlace',continue:'Continuar en este navegador',foot:'Esta guía no conecta wallets ni solicita frases de recuperación, claves privadas o PIN.',copied:'Enlace copiado. Pégalo en Safari para abrirlo.',failed:'No se pudo copiar automáticamente. Copia la dirección desde el menú del navegador.'},
    fr:{brand:'Guide de sécurité des portefeuilles crypto',label:'Pour une navigation plus fluide',title:'Ouvrir dans Safari',titleOther:'Ouvrir dans votre navigateur habituel',intro:'Sur iPhone, Safari peut offrir une expérience plus complète que certains navigateurs intégrés aux applications. Vous pouvez aussi continuer ici.',banner:'Guide éducatif indépendant sur la sécurité des portefeuilles',steps:'Copiez le lien, ouvrez Safari et collez l’adresse. Si votre appareil le permet, vous pouvez aussi essayer le bouton ci-dessous.',open:'Essayer d’ouvrir dans Safari',openOther:'Essayer dans le navigateur',copy:'Copier le lien',continue:'Continuer dans ce navigateur',foot:'Ce guide ne se connecte à aucun portefeuille et ne demande jamais de phrase de récupération, clé privée ou code PIN.',copied:'Lien copié. Collez-le dans Safari pour ouvrir la page.',failed:'Copie automatique impossible. Utilisez le menu du navigateur pour copier l’adresse.'},
    de:{brand:'Leitfaden zur Krypto-Wallet-Sicherheit',label:'Für ein besseres Surferlebnis',title:'Am besten in Safari öffnen',titleOther:'Im bevorzugten Browser öffnen',intro:'Auf dem iPhone bietet Safari möglicherweise ein vollständigeres Erlebnis als manche In-App-Browser. Sie können auch hier im aktuellen Browser fortfahren.',banner:'Unabhängige Aufklärung zur Wallet-Sicherheit',steps:'Kopieren Sie den Link, öffnen Sie Safari und fügen Sie die Adresse ein. Wenn Ihr Gerät es zulässt, können Sie auch die Schaltfläche unten ausprobieren.',open:'In Safari öffnen versuchen',openOther:'Im Browser öffnen versuchen',copy:'Seitenlink kopieren',continue:'In diesem Browser fortfahren',foot:'Dieser Leitfaden verbindet sich nicht mit Wallets und fragt niemals nach Wiederherstellungsphrase, privatem Schlüssel oder PIN.',copied:'Link kopiert. Fügen Sie ihn in Safari ein.',failed:'Automatisches Kopieren nicht möglich. Kopieren Sie die Adresse über das Browsermenü.'},
    ja:{brand:'暗号資産ウォレット安全ガイド',label:'より快適に閲覧するために',title:'Safariで開くことをおすすめします',titleOther:'お使いのブラウザーで開いてください',intro:'iPhoneでは、アプリ内ブラウザーよりSafariのほうが快適に表示できる場合があります。このまま現在のブラウザーで続けることもできます。',banner:'独立した暗号資産ウォレット安全ガイド',steps:'リンクをコピーしてSafariを開き、アドレスを貼り付けてください。端末で可能な場合は、下のボタンもお試しください。',open:'Safariで開いてみる',openOther:'ブラウザーで開いてみる',copy:'ページのリンクをコピー',continue:'このまま閲覧を続ける',foot:'ウォレットには接続せず、リカバリーフレーズ・秘密鍵・PINも求めません。',copied:'リンクをコピーしました。Safariに貼り付けてください。',failed:'自動コピーできませんでした。ブラウザーのメニューからURLをコピーしてください。'},
    ko:{brand:'암호화폐 지갑 보안 가이드',label:'더 편리한 브라우징 환경',title:'Safari에서 열기를 권장합니다',titleOther:'사용 중인 브라우저에서 열어 보세요',intro:'iPhone에서는 일부 앱 내 브라우저보다 Safari에서 페이지가 더 원활하게 표시될 수 있습니다. 현재 브라우저에서 계속 이용해도 됩니다.',banner:'독립적인 암호화폐 지갑 보안 교육 자료',steps:'링크를 복사한 뒤 Safari를 열고 주소를 붙여 넣으세요. 기기에서 지원하면 아래 버튼으로 열기를 시도할 수도 있습니다.',open:'Safari에서 열기 시도',openOther:'브라우저에서 열기 시도',copy:'페이지 링크 복사',continue:'현재 브라우저에서 계속',foot:'지갑에 연결하지 않으며 복구 문구, 개인 키, PIN을 요구하지 않습니다.',copied:'링크를 복사했습니다. Safari에 붙여 넣어 여세요.',failed:'자동 복사에 실패했습니다. 브라우저 메뉴에서 현재 주소를 복사하세요.'},
    pt:{brand:'Guia de segurança para carteiras cripto',label:'Uma navegação mais fluida',title:'Abra no Safari para melhor experiência',titleOther:'Abra no navegador de sua preferência',intro:'No iPhone, o Safari pode oferecer uma experiência mais completa do que alguns navegadores dentro de outros apps. Você também pode continuar aqui.',banner:'Educação independente sobre segurança de carteiras',steps:'Copie o link, abra o Safari e cole o endereço. Se o dispositivo permitir, você também pode tentar o botão abaixo.',open:'Tentar abrir no Safari',openOther:'Tentar abrir no navegador',copy:'Copiar link da página',continue:'Continuar neste navegador',foot:'Este guia não conecta carteiras nem solicita frase de recuperação, chave privada ou PIN.',copied:'Link copiado. Cole-o no Safari para abrir.',failed:'Não foi possível copiar automaticamente. Copie o endereço pelo menu do navegador.'}
  };
  const browserCopy={
    zh:{intro:'如果当前应用内浏览器显示或播放异常，建议复制链接后在 Safari（iPhone）或设备常用浏览器中打开。',steps:'点击“复制链接”，iPhone 用户打开 Safari 并粘贴网址；其他设备粘贴到常用浏览器。若系统允许，也可尝试下方按钮。',copied:'链接已复制，请粘贴到 Safari（iPhone）或常用浏览器打开。'},
    en:{intro:'If this in-app browser has display or playback issues, copy the link and open it in Safari on iPhone or your usual browser on another device.',steps:'Copy the link and paste it into Safari on iPhone, or your usual browser on another device. You can also try the button below if the system allows it.',copied:'Link copied. Paste it into Safari on iPhone or your usual browser on another device.'},
    es:{intro:'Si este navegador integrado muestra o reproduce la página con problemas, copia el enlace y ábrelo en Safari en iPhone o en tu navegador habitual en otros dispositivos.',steps:'Copia el enlace y pégalo en Safari en iPhone o en tu navegador habitual en otros dispositivos. También puedes probar el botón de abajo si el sistema lo permite.',copied:'Enlace copiado. Pégalo en Safari en iPhone o en tu navegador habitual en otros dispositivos.'},
    fr:{intro:'Si ce navigateur intégré affiche mal la page ou ne lit pas la vidéo, copiez le lien et ouvrez-le dans Safari sur iPhone ou dans votre navigateur habituel sur un autre appareil.',steps:'Copiez le lien et collez-le dans Safari sur iPhone ou dans votre navigateur habituel sur un autre appareil. Vous pouvez aussi essayer le bouton ci-dessous si le système le permet.',copied:'Lien copié. Collez-le dans Safari sur iPhone ou dans votre navigateur habituel sur un autre appareil.'},
    de:{intro:'Wenn dieser In-App-Browser die Seite nicht richtig anzeigt oder das Video nicht abspielt, kopieren Sie den Link und öffnen Sie ihn auf dem iPhone in Safari oder auf anderen Geräten im üblichen Browser.',steps:'Kopieren Sie den Link und fügen Sie ihn auf dem iPhone in Safari oder auf anderen Geräten in Ihren üblichen Browser ein. Sie können auch die Schaltfläche unten ausprobieren, sofern das System es zulässt.',copied:'Link kopiert. Fügen Sie ihn auf dem iPhone in Safari oder auf anderen Geräten in Ihren üblichen Browser ein.'},
    ja:{intro:'アプリ内ブラウザーで表示や動画再生に問題がある場合は、リンクをコピーし、iPhoneではSafari、その他の端末では普段のブラウザーで開いてください。',steps:'リンクをコピーし、iPhoneではSafariに、その他の端末では普段のブラウザーに貼り付けてください。システムが許可する場合は、下のボタンもお試しください。',copied:'リンクをコピーしました。iPhoneではSafariに、その他の端末では普段のブラウザーに貼り付けてください。'},
    ko:{intro:'앱 내 브라우저에서 화면 표시나 동영상 재생에 문제가 있으면 링크를 복사해 iPhone에서는 Safari로, 다른 기기에서는 평소 사용하는 브라우저로 여세요.',steps:'링크를 복사해 iPhone에서는 Safari에, 다른 기기에서는 평소 사용하는 브라우저에 붙여 넣으세요. 시스템에서 허용하면 아래 버튼도 시도할 수 있습니다.',copied:'링크를 복사했습니다. iPhone에서는 Safari에, 다른 기기에서는 평소 사용하는 브라우저에 붙여 넣으세요.'},
    pt:{intro:'Se este navegador integrado tiver problemas para exibir a página ou reproduzir o vídeo, copie o link e abra-o no Safari no iPhone ou no navegador habitual em outros dispositivos.',steps:'Copie o link e cole no Safari no iPhone ou no navegador habitual em outros dispositivos. Você também pode tentar o botão abaixo, se o sistema permitir.',copied:'Link copiado. Cole no Safari no iPhone ou no navegador habitual em outros dispositivos.'}
  };
  Object.entries(browserCopy).forEach(([locale,values])=>Object.assign(copy[locale],values));
  const languages=Object.keys(copy),normalize=x=>String(x||'').toLowerCase().split('-')[0],params=new URLSearchParams(location.search);
  let lang=normalize(params.get('lang'));
  if(!languages.includes(lang))lang=normalize(document.documentElement.lang);
  try{if(localStorage.getItem('walletGuideLanguageMode')==='manual')lang=normalize(localStorage.getItem('walletGuideLanguage'))||lang}catch(_){}
  if(!languages.includes(lang))lang=normalize(navigator.language);
  if(!languages.includes(lang))lang='en';
  const t=copy[lang],ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),openLabel=ios?t.open:t.openOther,title=ios?t.title:t.titleOther;
  const overlay=document.createElement('div');overlay.className='welcome-gate';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','welcome-title');overlay.setAttribute('aria-describedby','welcome-copy');
  overlay.innerHTML=`<section class="welcome-card"><div class="welcome-brand"><span class="welcome-mark" aria-hidden="true"><svg viewBox="0 0 32 32" width="24" height="24" fill="none"><circle cx="16" cy="16" r="12.5" stroke="currentColor" stroke-width="1.8"/><path d="m20.8 10.3-3.5 8.1-6.1 3.3 3.1-7.9 6.5-3.5Z" fill="#cce78a" stroke="#cce78a" stroke-linejoin="round"/><path d="m20.8 10.3-3.5 8.1-3-4.6 6.5-3.5Z" fill="#f7fff0"/></svg></span><div class="welcome-brand-copy">${t.brand}<small>PAUSE · CHECK · THEN SIGN</small></div></div><div class="welcome-label"><span aria-hidden="true">◈</span>${t.label}</div><h1 class="welcome-title" id="welcome-title">${title}</h1><p class="welcome-copy" id="welcome-copy">${t.intro}</p><div class="welcome-banner">${t.banner}</div><div class="welcome-instructions">${t.steps}</div><div class="welcome-actions"><button class="welcome-action welcome-action-primary" type="button" data-open>${openLabel}<span aria-hidden="true">↗</span></button><button class="welcome-action welcome-action-dark" type="button" data-copy>${t.copy}<span aria-hidden="true">▢</span></button></div><p class="welcome-footnote">${t.foot}</p><div class="welcome-status" role="status" aria-live="polite" hidden></div></section>`;
  document.body.append(overlay);document.body.style.overflow='hidden';
  const background=[...document.body.children].filter(node=>node!==overlay),inertState=background.map(node=>node.inert);background.forEach(node=>{node.inert=true});
  overlay.querySelector('[data-open]').addEventListener('click',()=>{window.open(location.href,'_blank','noopener');});
  overlay.querySelector('[data-copy]').addEventListener('click',async()=>{const status=overlay.querySelector('.welcome-status');try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(location.href);else{const field=document.createElement('textarea');field.value=location.href;field.style.cssText='position:fixed;left:-9999px;top:0';document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();if(!ok)throw new Error('copy failed')}status.textContent=t.copied}catch(_){status.textContent=t.failed}status.hidden=false});
  overlay.querySelector('[data-open]').focus({preventScroll:true});
})();
