(()=>{
  const copy={
    zh:{brand:'加密钱包安全指南',label:'从应用内浏览器切换',title:'在 Safari 中继续浏览',titleOther:'在外部浏览器中继续',intro:'如果你从 Facebook 或 YouTube 点开本页，请点应用内浏览器右上角菜单，选择“在外部浏览器打开”。若 Safari 是 iPhone 的默认浏览器，页面就会在 Safari 中打开。',banner:'先核对，再签名 · 钱包安全第一步',steps:'也可以点下方按钮尝试打开外部浏览器。应用可能会阻止自动切换；此时请用右上角菜单选择“在外部浏览器打开”，或复制链接后粘贴到 Safari。',open:'尝试打开外部浏览器',openOther:'尝试打开外部浏览器',copy:'复制网页链接',continue:'继续浏览本页',foot:'本页不会连接钱包，也不会索取助记词、私钥或 PIN。',copied:'链接已复制。请打开 Safari 并粘贴网址。',failed:'无法自动复制，请使用浏览器菜单复制当前网址。'},
    en:{brand:'Crypto Wallet Safety Guide',label:'Continue outside the in-app browser',title:'Continue in Safari',titleOther:'Continue in an external browser',intro:'If you opened this page from Facebook or YouTube, tap the menu in the in-app browser and choose “Open in external browser.” If Safari is your iPhone’s default browser, the page will open in Safari.',banner:'Pause · Verify · Then Sign',steps:'You can also try the button below. The app may block automatic switching; if it does, use the menu to open the page externally, or copy the link and paste it into Safari.',open:'Try opening an external browser',openOther:'Try opening an external browser',copy:'Copy page link',continue:'Continue in this browser',foot:'This guide does not connect to wallets or ask for recovery phrases, private keys or PINs.',copied:'Link copied. Open Safari and paste the address.',failed:'Could not copy automatically. Use your browser menu to copy this page address.'},
    es:{brand:'Guía de seguridad para wallets',label:'Continuar fuera del navegador integrado',title:'Continuar en Safari',titleOther:'Continuar en un navegador externo',intro:'Si abriste esta página desde Facebook o YouTube, toca el menú del navegador integrado y elige «Abrir en navegador externo». Si Safari es el navegador predeterminado de tu iPhone, la página se abrirá allí.',banner:'Pausa · Verifica · Firma solo cuando estés seguro',steps:'También puedes probar el botón de abajo. La aplicación puede impedir el cambio automático; si ocurre, abre el menú y elige «Abrir en navegador externo», o copia el enlace y pégalo en Safari.',open:'Probar a abrir un navegador externo',openOther:'Probar a abrir un navegador externo',copy:'Copiar enlace',continue:'Continuar en este navegador',foot:'Esta guía no conecta wallets ni solicita frases de recuperación, claves privadas o PIN.',copied:'Enlace copiado. Abre Safari y pega la dirección.',failed:'No se pudo copiar automáticamente. Copia la dirección desde el menú del navegador.'},
    fr:{brand:'Guide de sécurité des portefeuilles crypto',label:'Continuer hors du navigateur intégré',title:'Continuer dans Safari',titleOther:'Continuer dans un navigateur externe',intro:'Si vous avez ouvert cette page depuis Facebook ou YouTube, touchez le menu du navigateur intégré et choisissez « Ouvrir dans un navigateur externe ». Si Safari est le navigateur par défaut de votre iPhone, la page s’y ouvrira.',banner:'Faites une pause · Vérifiez · Puis signez',steps:'Vous pouvez aussi essayer le bouton ci-dessous. L’application peut bloquer le changement automatique ; dans ce cas, ouvrez le menu et choisissez « Ouvrir dans un navigateur externe », ou copiez le lien et collez-le dans Safari.',open:'Essayer d’ouvrir un navigateur externe',openOther:'Essayer d’ouvrir un navigateur externe',copy:'Copier le lien',continue:'Continuer dans ce navigateur',foot:'Ce guide ne se connecte à aucun portefeuille et ne demande jamais de phrase de récupération, clé privée ou code PIN.',copied:'Lien copié. Ouvrez Safari et collez l’adresse.',failed:'Copie automatique impossible. Utilisez le menu du navigateur pour copier l’adresse.'},
    de:{brand:'Leitfaden zur Krypto-Wallet-Sicherheit',label:'Außerhalb des In-App-Browsers fortfahren',title:'In Safari fortfahren',titleOther:'In einem externen Browser fortfahren',intro:'Wenn Sie diese Seite über Facebook oder YouTube geöffnet haben, tippen Sie im In-App-Browser auf das Menü und wählen Sie „In externem Browser öffnen“. Ist Safari der Standardbrowser Ihres iPhones, wird die Seite dort geöffnet.',banner:'Erst prüfen · Dann sicher signieren',steps:'Sie können auch die Schaltfläche unten ausprobieren. Die App kann den automatischen Wechsel blockieren. Öffnen Sie dann das Menü und wählen Sie „In externem Browser öffnen“, oder kopieren Sie den Link und fügen Sie ihn in Safari ein.',open:'Externen Browser öffnen versuchen',openOther:'Externen Browser öffnen versuchen',copy:'Seitenlink kopieren',continue:'In diesem Browser fortfahren',foot:'Dieser Leitfaden verbindet sich nicht mit Wallets und fragt niemals nach Wiederherstellungsphrase, privatem Schlüssel oder PIN.',copied:'Link kopiert. Öffnen Sie Safari und fügen Sie die Adresse ein.',failed:'Automatisches Kopieren nicht möglich. Kopieren Sie die Adresse über das Browsermenü.'},
    ja:{brand:'暗号資産ウォレット安全ガイド',label:'アプリ内ブラウザーの外で開く',title:'Safariで続ける',titleOther:'外部ブラウザーで続ける',intro:'FacebookやYouTubeから開いた場合は、アプリ内ブラウザーのメニューで「外部ブラウザーで開く」を選んでください。iPhoneのデフォルトブラウザーがSafariなら、Safariで開きます。',banner:'確認してから署名 · ウォレットを守る',steps:'下のボタンから外部ブラウザーで開くことも試せます。アプリが自動切り替えを制限する場合は、メニューから外部ブラウザーを選ぶか、リンクをコピーしてSafariに貼り付けてください。',open:'外部ブラウザーで開く',openOther:'外部ブラウザーで開く',copy:'ページのリンクをコピー',continue:'このまま閲覧を続ける',foot:'ウォレットには接続せず、リカバリーフレーズ・秘密鍵・PINも求めません。',copied:'リンクをコピーしました。Safariを開いて貼り付けてください。',failed:'自動コピーできませんでした。ブラウザーのメニューからURLをコピーしてください。'},
    ko:{brand:'암호화폐 지갑 보안 가이드',label:'앱 내 브라우저 밖에서 열기',title:'Safari에서 계속하기',titleOther:'외부 브라우저에서 계속하기',intro:'Facebook이나 YouTube에서 이 페이지를 열었다면 앱 내 브라우저 메뉴에서 “외부 브라우저에서 열기”를 선택하세요. iPhone의 기본 브라우저가 Safari이면 Safari에서 열립니다.',banner:'확인한 다음 서명하세요 · 지갑 안전 우선',steps:'아래 버튼으로 외부 브라우저 열기도 시도할 수 있습니다. 앱이 자동 전환을 막으면 메뉴에서 외부 브라우저를 선택하거나 링크를 복사해 Safari에 붙여 넣으세요.',open:'외부 브라우저 열기 시도',openOther:'외부 브라우저 열기 시도',copy:'페이지 링크 복사',continue:'현재 브라우저에서 계속',foot:'지갑에 연결하지 않으며 복구 문구, 개인 키, PIN을 요구하지 않습니다.',copied:'링크를 복사했습니다. Safari를 열어 붙여 넣으세요.',failed:'자동 복사에 실패했습니다. 브라우저 메뉴에서 현재 주소를 복사하세요.'},
    pt:{brand:'Guia de segurança para carteiras cripto',label:'Continuar fora do navegador do app',title:'Continuar no Safari',titleOther:'Continuar em um navegador externo',intro:'Se você abriu esta página pelo Facebook ou YouTube, toque no menu do navegador do app e escolha “Abrir no navegador externo”. Se o Safari for o navegador padrão do iPhone, a página será aberta nele.',banner:'Pare · Confira · Só então assine',steps:'Você também pode tentar o botão abaixo. O app pode bloquear a troca automática; nesse caso, use o menu para abrir no navegador externo ou copie o link e cole no Safari.',open:'Tentar abrir navegador externo',openOther:'Tentar abrir navegador externo',copy:'Copiar link da página',continue:'Continuar neste navegador',foot:'Este guia não conecta carteiras nem solicita frase de recuperação, chave privada ou PIN.',copied:'Link copiado. Abra o Safari e cole o endereço.',failed:'Não foi possível copiar automaticamente. Copie o endereço pelo menu do navegador.'}
  };
  const languages=Object.keys(copy),normalize=x=>String(x||'').toLowerCase().split('-')[0],params=new URLSearchParams(location.search);
  let lang=normalize(params.get('lang'));
  if(!languages.includes(lang))lang=normalize(document.documentElement.lang);
  try{if(localStorage.getItem('walletGuideLanguageMode')==='manual')lang=normalize(localStorage.getItem('walletGuideLanguage'))||lang}catch(_){}
  if(!languages.includes(lang))lang=normalize(navigator.language);
  if(!languages.includes(lang))lang='en';
  const t=copy[lang],ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1),openLabel=ios?t.open:t.openOther,title=ios?t.title:t.titleOther;
  const overlay=document.createElement('div');overlay.className='welcome-gate';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','welcome-title');overlay.setAttribute('aria-describedby','welcome-copy');
  overlay.innerHTML=`<section class="welcome-card"><div class="welcome-brand"><span class="welcome-mark" aria-hidden="true"><svg viewBox="0 0 32 32" width="24" height="24" fill="none"><circle cx="16" cy="16" r="12.5" stroke="currentColor" stroke-width="1.8"/><path d="m20.8 10.3-3.5 8.1-6.1 3.3 3.1-7.9 6.5-3.5Z" fill="#cce78a" stroke="#cce78a" stroke-linejoin="round"/><path d="m20.8 10.3-3.5 8.1-3-4.6 6.5-3.5Z" fill="#f7fff0"/></svg></span><div class="welcome-brand-copy">${t.brand}<small>PAUSE · CHECK · THEN SIGN</small></div></div><div class="welcome-label"><span aria-hidden="true">◈</span>${t.label}</div><h1 class="welcome-title" id="welcome-title">${title}</h1><p class="welcome-copy" id="welcome-copy">${t.intro}</p><div class="welcome-banner">${t.banner}</div><div class="welcome-instructions">${t.steps}</div><div class="welcome-actions"><button class="welcome-action welcome-action-primary" type="button" data-open>${openLabel}<span aria-hidden="true">↗</span></button><button class="welcome-action welcome-action-dark" type="button" data-copy>${t.copy}<span aria-hidden="true">▢</span></button></div><p class="welcome-footnote">${t.foot}</p><div class="welcome-status" role="status" aria-live="polite" hidden></div></section>`;
  document.body.append(overlay);document.body.style.overflow='hidden';
  const background=[...document.body.children].filter(node=>node!==overlay),inertState=background.map(node=>node.inert);background.forEach(node=>{node.inert=true});
  overlay.querySelector('[data-open]').addEventListener('click',()=>{window.open(location.href,'_blank','noopener');});
  overlay.querySelector('[data-copy]').addEventListener('click',async()=>{const status=overlay.querySelector('.welcome-status');try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(location.href);else{const field=document.createElement('textarea');field.value=location.href;field.style.cssText='position:fixed;left:-9999px;top:0';document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();if(!ok)throw new Error('copy failed')}status.textContent=t.copied}catch(_){status.textContent=t.failed}status.hidden=false});
  overlay.querySelector('[data-open]').focus({preventScroll:true});
})();
